services:
  db:
    image: postgres:15-alpine
    container_name: hrm_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hrm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: hrm_adminer
    restart: always
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    container_name: hrm_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    container_name: hrm_minio_mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/hrm-uploads;
      /usr/bin/mc anonymous set public myminio/hrm-uploads;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
