import {
  EmployeeDetail,
  EmployeeReportRow,
  AttendanceRecord,
  LeaveHistoryRecord,
  SummaryCardItem,
  ViolationRecord,
  ReportPeriod,
} from "./types";

export const summaryCardsByPeriod: Record<ReportPeriod, SummaryCardItem[]> = {
  weekly: [
    { label: "Total Employees", value: 5 },
    { label: "Total Leave Used", value: 9 },
    { label: "Pending Requests", value: 2 },
    { label: "Avg Remaining", value: 18 },
  ],
  monthly: [
    { label: "Total Employees", value: 5 },
    { label: "Total Leave Used", value: 46 },
    { label: "Pending Requests", value: 6 },
    { label: "Avg Remaining", value: 10 },
  ],
  annually: [
    { label: "Total Employees", value: 5 },
    { label: "Total Leave Used", value: 132 },
    { label: "Pending Requests", value: 11 },
    { label: "Avg Remaining", value: 7 },
  ],
};

export const employeeReportRowsByPeriod: Record<ReportPeriod, EmployeeReportRow[]> = {
  weekly: [
    {
      id: "EMP001",
      name: "Sarah Johnson",
      employeeCode: "EMP001",
      role: "Manager",
      department: "Engineering",
      totalLeave: 2,
      used: 1,
      pending: 0,
      remaining: 1,
      lastLeave: "Jan 5, 2025",
    },
    {
      id: "EMP002",
      name: "Mike Chen",
      employeeCode: "EMP002",
      role: "Senior Dev",
      department: "Marketing",
      totalLeave: 2,
      used: 0,
      pending: 1,
      remaining: 1,
      lastLeave: "Jan 4, 2025",
    },
    {
      id: "EMP003",
      name: "Emily Davis",
      employeeCode: "EMP003",
      role: "Senior Developer",
      department: "Engineering",
      totalLeave: 2,
      used: 1,
      pending: 0,
      remaining: 1,
      lastLeave: "Jan 3, 2025",
    },
    {
      id: "EMP004",
      name: "John Perera",
      employeeCode: "EMP004",
      role: "HR Executive",
      department: "HR",
      totalLeave: 2,
      used: 0,
      pending: 0,
      remaining: 2,
      lastLeave: "Jan 2, 2025",
    },
    {
      id: "EMP005",
      name: "Anne Silva",
      employeeCode: "EMP005",
      role: "Developer",
      department: "Engineering",
      totalLeave: 2,
      used: 1,
      pending: 1,
      remaining: 0,
      lastLeave: "Jan 6, 2025",
    },
  ],

  monthly: [
    {
      id: "EMP001",
      name: "Sarah Johnson",
      employeeCode: "EMP001",
      role: "Manager",
      department: "Engineering",
      totalLeave: 30,
      used: 8,
      pending: 2,
      remaining: 10,
      lastLeave: "Jan 5, 2025",
    },
    {
      id: "EMP002",
      name: "Mike Chen",
      employeeCode: "EMP002",
      role: "Senior Dev",
      department: "Marketing",
      totalLeave: 30,
      used: 12,
      pending: 0,
      remaining: 6,
      lastLeave: "Jan 10, 2025",
    },
    {
      id: "EMP003",
      name: "Emily Davis",
      employeeCode: "EMP003",
      role: "Senior Developer",
      department: "Engineering",
      totalLeave: 30,
      used: 8,
      pending: 2,
      remaining: 12,
      lastLeave: "Jan 5, 2025",
    },
    {
      id: "EMP004",
      name: "John Perera",
      employeeCode: "EMP004",
      role: "HR Executive",
      department: "HR",
      totalLeave: 30,
      used: 14,
      pending: 1,
      remaining: 9,
      lastLeave: "Jan 12, 2025",
    },
    {
      id: "EMP005",
      name: "Anne Silva",
      employeeCode: "EMP005",
      role: "Developer",
      department: "Engineering",
      totalLeave: 30,
      used: 4,
      pending: 1,
      remaining: 15,
      lastLeave: "Jan 8, 2025",
    },
  ],

  annually: [
    {
      id: "EMP001",
      name: "Sarah Johnson",
      employeeCode: "EMP001",
      role: "Manager",
      department: "Engineering",
      totalLeave: 365,
      used: 28,
      pending: 4,
      remaining: 18,
      lastLeave: "Dec 15, 2025",
    },
    {
      id: "EMP002",
      name: "Mike Chen",
      employeeCode: "EMP002",
      role: "Senior Dev",
      department: "Marketing",
      totalLeave: 365,
      used: 22,
      pending: 1,
      remaining: 24,
      lastLeave: "Nov 10, 2025",
    },
    {
      id: "EMP003",
      name: "Emily Davis",
      employeeCode: "EMP003",
      role: "Senior Developer",
      department: "Engineering",
      totalLeave: 365,
      used: 31,
      pending: 3,
      remaining: 12,
      lastLeave: "Dec 20, 2025",
    },
    {
      id: "EMP004",
      name: "John Perera",
      employeeCode: "EMP004",
      role: "HR Executive",
      department: "HR",
      totalLeave: 365,
      used: 19,
      pending: 1,
      remaining: 20,
      lastLeave: "Oct 12, 2025",
    },
    {
      id: "EMP005",
      name: "Anne Silva",
      employeeCode: "EMP005",
      role: "Developer",
      department: "Engineering",
      totalLeave: 365,
      used: 32,
      pending: 2,
      remaining: 10,
      lastLeave: "Dec 8, 2025",
    },
  ],
};

export const departments = [
  "All Departments",
  "Engineering",
  "Marketing",
  "HR",
];

// keep your existing detail data below
export const employeeDetails: Record<string, EmployeeDetail> = {
  EMP001: {
    id: "EMP001",
    name: "Sarah Johnson",
    employeeCode: "EMP001",
    department: "Engineering",
    position: "Manager",
    manager: "John Smith",
    joinDate: "Jan 15, 2023",
    attendanceRate: 86,
    absentDays: 3,
    lateArrivals: 2,
    totalViolations: 2,
  },
  EMP002: {
    id: "EMP002",
    name: "Mike Chen",
    employeeCode: "EMP002",
    department: "Marketing",
    position: "Senior Dev",
    manager: "Anne Silva",
    joinDate: "Feb 5, 2023",
    attendanceRate: 91,
    absentDays: 1,
    lateArrivals: 0,
    totalViolations: 0,
  },
  EMP003: {
    id: "EMP003",
    name: "Emily Davis",
    employeeCode: "EMP003",
    department: "Engineering",
    position: "Senior Developer",
    manager: "John Smith",
    joinDate: "Jan 15, 2023",
    attendanceRate: 68,
    absentDays: 3,
    lateArrivals: 4,
    totalViolations: 5,
  },
  EMP004: {
    id: "EMP004",
    name: "John Perera",
    employeeCode: "EMP004",
    department: "HR",
    position: "HR Executive",
    manager: "Nadeesha Silva",
    joinDate: "Mar 12, 2023",
    attendanceRate: 89,
    absentDays: 2,
    lateArrivals: 1,
    totalViolations: 1,
  },
  EMP005: {
    id: "EMP005",
    name: "Anne Silva",
    employeeCode: "EMP005",
    department: "Engineering",
    position: "Developer",
    manager: "John Smith",
    joinDate: "Apr 18, 2023",
    attendanceRate: 93,
    absentDays: 1,
    lateArrivals: 0,
    totalViolations: 0,
  },
};

export const attendanceByEmployee: Record<string, AttendanceRecord[]> = {
  EMP001: [
    {
      employeeName: "Sarah Johnson",
      employeeCode: "EMP001",
      department: "Engineering",
      present: 19,
      absent: 3,
      totalDays: 22,
      rate: 86,
      trend: "Declining",
    },
  ],
  EMP002: [
    {
      employeeName: "Mike Chen",
      employeeCode: "EMP002",
      department: "Marketing",
      present: 20,
      absent: 2,
      totalDays: 22,
      rate: 91,
      trend: "Improving",
    },
  ],
  EMP003: [
    {
      employeeName: "Emily Davis",
      employeeCode: "EMP003",
      department: "Engineering",
      present: 19,
      absent: 3,
      totalDays: 22,
      rate: 86,
      trend: "Declining",
    },
  ],
};

export const leaveHistoryByEmployee: Record<string, LeaveHistoryRecord[]> = {
  EMP003: [
    {
      type: "Annual Leave",
      startDate: "Jan 27, 2025",
      endDate: "Jan 28, 2025",
      days: 2,
      reason: "Family vacation",
      status: "APPROVED",
    },
    {
      type: "Sick Leave",
      startDate: "Jan 15, 2025",
      endDate: "Jan 17, 2025",
      days: 3,
      reason: "Flu symptoms",
      status: "APPROVED",
    },
    {
      type: "Personal Leave",
      startDate: "Dec 20, 2024",
      endDate: "Dec 20, 2024",
      days: 1,
      reason: "Personal matter",
      status: "APPROVED",
    },
    {
      type: "Sick Leave",
      startDate: "Dec 5, 2024",
      endDate: "Dec 6, 2024",
      days: 2,
      reason: "Medical checkup",
      status: "APPROVED",
    },
  ],
};

export const violationsByEmployee: Record<string, ViolationRecord[]> = {
  EMP003: [
    {
      title: "Unauthorized Absence",
      date: "Jan 13, 2025",
      description: "Absent without prior notice or approval",
      severity: "HIGH SEVERITY",
    },
    {
      title: "Unauthorized Absence",
      date: "Jan 13, 2025",
      description: "Did not report to work without notification",
      severity: "HIGH SEVERITY",
    },
    {
      title: "Late Arrival",
      date: "Jan 22, 2025",
      description: "Arrived 2 hours late without valid reason",
      severity: "MEDIUM SEVERITY",
    },
    {
      title: "Late Arrival",
      date: "Jan 22, 2025",
      description: "Arrived 1.5 hours late",
      severity: "MEDIUM SEVERITY",
    },
    {
      title: "Early Departure",
      date: "Feb 5, 2025",
      description: "Left 2 hours early without approval",
      severity: "MEDIUM SEVERITY",
    },
  ],
};