"""add_roles_departments_users_schema

Revision ID: 008823d50b11
Revises: 61c0e942bd40
Create Date: 2026-04-23 12:04:54.663317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008823d50b11'
down_revision: Union[str, Sequence[str], None] = '61c0e942bd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['user_id'])
    op.drop_constraint(op.f('employees_role_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.drop_column('employees', 'role_id')
    op.drop_column('employees', 'department')
    # Permissions: add as nullable first, copy data, then make NOT NULL
    op.add_column('permissions', sa.Column('permission_name', sa.String(length=100), nullable=True))
    op.add_column('permissions', sa.Column('resource', sa.String(length=100), nullable=True))
    op.add_column('permissions', sa.Column('action', sa.String(length=100), nullable=True))
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # Copy existing `name` -> `permission_name` so NOT NULL constraint can be applied
    op.execute("UPDATE permissions SET permission_name = name WHERE permission_name IS NULL")
    op.alter_column('permissions', 'permission_name', nullable=False)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_permission_name'), 'permissions', ['permission_name'], unique=True)
    op.drop_column('permissions', 'name')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # Roles: add as nullable first, copy data, then make NOT NULL
    op.add_column('roles', sa.Column('role_name', sa.String(length=100), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # Copy existing `name` -> `role_name`
    op.execute("UPDATE roles SET role_name = name WHERE role_name IS NULL")
    op.alter_column('roles', 'role_name', nullable=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.drop_column('roles', 'is_system')
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('is_system', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'role_name')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_permissions_permission_name'), table_name='permissions')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.drop_column('permissions', 'created_at')
    op.drop_column('permissions', 'action')
    op.drop_column('permissions', 'resource')
    op.drop_column('permissions', 'permission_name')
    op.add_column('employees', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_role_id_fkey'), 'employees', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'user_id')
    op.drop_column('employees', 'department_id')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
