"""add_extra_employee_fields

Revision ID: 61c0e942bd40
Revises: d5298cc586be
Create Date: 2026-04-20 16:07:54.540745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c0e942bd40'
down_revision: Union[str, Sequence[str], None] = 'd5298cc586be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('qualifications', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('bank_account_no', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('bank_branch', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'bank_branch')
    op.drop_column('employees', 'bank_account_no')
    op.drop_column('employees', 'bank_name')
    op.drop_column('employees', 'qualifications')
    op.drop_column('employees', 'skills')
    op.drop_column('employees', 'emergency_contact_relation')
    op.drop_column('employees', 'emergency_contact_phone')
    op.drop_column('employees', 'emergency_contact_name')
    # ### end Alembic commands ###
