"""Add auto_prorated_leaves_credited

Revision ID: 6979a8f61482
Revises: 23a865db923c
Create Date: 2026-07-16 12:42:25.436853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6979a8f61482'
down_revision: Union[str, Sequence[str], None] = '23a865db923c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_templates_id'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_document_audit_logs_request_id'), table_name='document_audit_logs')
    op.drop_table('document_audit_logs')
    op.drop_table('document_requests')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_table('employee_documents')
    op.add_column('employee_designation_history', sa.Column('auto_prorated_leaves_credited', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('uix_employee_leave_type_year'), 'employee_leave_entitlements', type_='unique')
    op.create_unique_constraint('uix_employee_leave_type', 'employee_leave_entitlements', ['employee_id', 'leave_type_id'])
    op.drop_column('employee_leave_entitlements', 'year')
    op.drop_column('employees', 'probation_months')
    op.drop_column('employees', 'probation_end_date')
    op.drop_constraint(op.f('leave_requests_parent_request_id_fkey'), 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'leave_requests', ['parent_request_id'], ['leave_request_id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_overtime_threshold_effective'), table_name='overtime_threshold_history')
    op.drop_index(op.f('idx_time_check_pairs_user_date'), table_name='time_check_pairs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_time_check_pairs_user_date'), 'time_check_pairs', ['user_id', 'date'], unique=False)
    op.create_index(op.f('idx_overtime_threshold_effective'), 'overtime_threshold_history', ['effective_date'], unique=False)
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key(op.f('leave_requests_parent_request_id_fkey'), 'leave_requests', 'leave_requests', ['parent_request_id'], ['leave_request_id'])
    op.add_column('employees', sa.Column('probation_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('probation_months', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True))
    op.add_column('employee_leave_entitlements', sa.Column('year', sa.INTEGER(), server_default=sa.text('2026'), autoincrement=False, nullable=True))
    op.drop_constraint('uix_employee_leave_type', 'employee_leave_entitlements', type_='unique')
    op.create_unique_constraint(op.f('uix_employee_leave_type_year'), 'employee_leave_entitlements', ['employee_id', 'leave_type_id', 'year'], postgresql_nulls_not_distinct=False)
    op.drop_column('employee_designation_history', 'auto_prorated_leaves_credited')
    op.create_table('employee_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('is_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('UPLOADED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='documentstatus'), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employee_documents_pkey'))
    )
    op.create_table('document_types',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=20), server_default=sa.text("'UPLOAD'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_types_pkey')),
    sa.UniqueConstraint('name', name=op.f('document_types_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.create_table('document_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('requester_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('requester_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'APPROVED', 'COMPLETED', 'REJECTED', name='requeststatus'), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_document_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_requests_pkey'))
    )
    op.create_table('document_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('changed_by_employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('document_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_document_audit_logs_request_id'), 'document_audit_logs', ['request_id'], unique=False)
    op.create_table('document_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('template_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_templates_pkey'))
    )
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    # ### end Alembic commands ###
