"""Add auto_prorated_leaves_credited

Revision ID: 6979a8f61482
Revises: 23a865db923c
Create Date: 2026-07-16 12:42:25.436853

NOTE: the original autogenerated body of this migration also dropped the five
document tables (document_templates, document_types, document_requests,
document_audit_logs, employee_documents) and several employee/leave columns.
Those drops were an autogenerate artifact, not an intended change: alembic/env.py
could not see the document models, so it treated their live tables as orphans.
Only the auto_prorated_leaves_credited column below was ever intended, so the
destructive operations have been removed.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6979a8f61482'
down_revision: Union[str, Sequence[str], None] = '23a865db923c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Idempotent: this revision may already have been applied on machines that
    # ran the original autogenerated version.
    op.execute(
        "ALTER TABLE employee_designation_history "
        "ADD COLUMN IF NOT EXISTS auto_prorated_leaves_credited "
        "BOOLEAN NOT NULL DEFAULT FALSE"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "ALTER TABLE employee_designation_history "
        "DROP COLUMN IF EXISTS auto_prorated_leaves_credited"
    )
