"""Add is_active to leave_types

Revision ID: 77e63f4240ef
Revises: e1f2a3b4c5d6
Create Date: 2026-07-21 08:37:22.138304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77e63f4240ef'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prorated_credit_logs_id'), table_name='prorated_credit_logs')
    op.drop_table('prorated_credit_logs')
    op.add_column('candidates', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('candidates', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_candidates_content_hash'), 'candidates', ['content_hash'], unique=False)
    op.drop_column('employee_designation_history', 'auto_prorated_leaves_credited')
    op.add_column('leave_types', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_folder'), table_name='notifications')
    op.drop_index(op.f('idx_overtime_threshold_effective'), table_name='overtime_threshold_history')
    op.drop_index(op.f('idx_time_check_pairs_user_date'), table_name='time_check_pairs')
    op.add_column('vacancies', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'department_id')
    op.create_index(op.f('idx_time_check_pairs_user_date'), 'time_check_pairs', ['user_id', 'date'], unique=False)
    op.create_index(op.f('idx_overtime_threshold_effective'), 'overtime_threshold_history', ['effective_date'], unique=False)
    op.create_index(op.f('ix_notifications_user_folder'), 'notifications', ['user_id', 'is_deleted', 'is_archived'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.drop_column('leave_types', 'is_active')
    op.add_column('employee_designation_history', sa.Column('auto_prorated_leaves_credited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_candidates_content_hash'), table_name='candidates')
    op.drop_column('candidates', 'content_hash')
    op.drop_column('candidates', 'source')
    op.create_table('prorated_credit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credited_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trigger', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('prorated_credit_logs_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('prorated_credit_logs_leave_type_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('prorated_credit_logs_pkey')),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'leave_year', name=op.f('uix_prorated_credit_emp_type_year'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_prorated_credit_logs_id'), 'prorated_credit_logs', ['id'], unique=False)
    # ### end Alembic commands ###
