"""Add dynamic designation system

Revision ID: a82f12e7086f
Revises: f3c1a2b4d7e8
Create Date: 2026-07-04 20:08:12.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a82f12e7086f"
down_revision: Union[str, None] = "f3c1a2b4d7e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.engine.reflection import Inspector
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    existing_tables = inspector.get_table_names()

    # Create 'designations' table only if it doesn't exist
    if "designations" not in existing_tables:
        op.create_table(
            "designations",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("name"),
        )
        op.create_index(op.f("ix_designations_id"), "designations", ["id"], unique=False)

    # Create 'employee_designation_history' table only if it doesn't exist
    if "employee_designation_history" not in existing_tables:
        op.create_table(
            "employee_designation_history",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("employee_id", sa.Integer(), nullable=False),
            sa.Column("designation_id", sa.Integer(), nullable=True),
            sa.Column("designation_name", sa.String(length=100), nullable=False),
            sa.Column("start_date", sa.Date(), nullable=False),
            sa.Column("end_date", sa.Date(), nullable=True),
            sa.Column("leave_overrides", sa.JSON(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.ForeignKeyConstraint(["designation_id"], ["designations.id"], ondelete="SET NULL"),
            sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_employee_designation_history_id"), "employee_designation_history", ["id"], unique=False)

    # Add 'designation_id' column to 'employees' only if it doesn't exist
    existing_employee_cols = [c["name"] for c in inspector.get_columns("employees")]
    if "designation_id" not in existing_employee_cols:
        op.add_column("employees", sa.Column("designation_id", sa.Integer(), nullable=True))
        op.create_foreign_key(None, "employees", "designations", ["designation_id"], ["id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employees", type_="foreignkey")
    op.drop_column("employees", "designation_id")
    op.drop_index(op.f("ix_employee_designation_history_id"), table_name="employee_designation_history")
    op.drop_table("employee_designation_history")
    op.drop_index(op.f("ix_designations_id"), table_name="designations")
    op.drop_table("designations")
    # ### end Alembic commands ###
