"""Add personal fields to employees

Revision ID: d5298cc586be
Revises: 0908997b26ae
Create Date: 2026-04-11 12:21:55.268438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5298cc586be'
down_revision: Union[str, Sequence[str], None] = '0908997b26ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('nationality', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'nationality')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'date_of_birth')
    # ### end Alembic commands ###
